### PR TITLE
New methods for accounts.

### PR DESCRIPTION
**Pull request by chevdor**
Hello,
Here is a pull request for 2 methods I could not find in your package.

### CODE REVIEW

**Comment by emilioTe** [comment]
Any chance you can remove the .gitignore? Besides that I'd be more than happy to merge this.

**Comment by chevdor** [comment]
Hello Emilio,
I sure can and don't mind.
Although would you mind explaining why?

**Comment by emilioTe** [comment]
I don't like to include configuration files in packages unless they are necessary. Thanks.
On Mon, Feb 09, 2015 at 5:48 PM, Chevdor <notifications@github.com> wrote:Hello Emilio,
I sure can and don't mind.
Although would you mind explaining why?

**Comment by lorensr** [comment]
GitHub recommends including it

https://help.github.com/articles/ignoring-files/

**Comment by emilioTe** [comment]
@lorensr Until now I was the only one contributing to this repo meaning I had no need for the .gitignore. But seeing as how this is now an issue it can be merged in.

@chevdor Merging as is.

**Pull request merged**
